"""Lint, simulation, waveforms and cleanup."""

from __future__ import annotations

import shutil
import xml.etree.ElementTree as ET
from pathlib import Path

from . import meta, tools, ui, workspace
from .ui import Abort

WAVE_SUFFIXES = (".fst", ".vcd", ".ghw")
VIEWERS = ("surfer", "gtkwave")

FRAMEWORKS = ("cocotb", "sv")

# Log of a plain SystemVerilog run; `flow ls` uses it as the "was simulated" mark.
SIM_LOG = "sim.log"
BUILD_LOG = "build.log"

# How a SystemVerilog testbench reports its verdict (see templates/sv_tb.sv).
PASS_MARKER = "TEST PASSED"
FAIL_MARKERS = ("TEST FAILED", "%Error", "$fatal", "Fatal:")

RUNNER = '''#!/usr/bin/env python3
"""Generated by `flow sim` on {stamp} -- edits here are overwritten."""

import sys
from pathlib import Path

try:
    from cocotb_tools.runner import get_runner          # cocotb >= 2.0
except ImportError:  # pragma: no cover
    try:
        from cocotb.runner import get_runner            # cocotb 1.7 / 1.8
    except ImportError:
        sys.exit("cocotb is not installed  ->  pip install cocotb")

runner = get_runner({simulator!r})

runner.build(
    verilog_sources=[Path(p) for p in {sources!r}],
    includes=[Path(p) for p in {includes!r}],
    defines={defines!r},
    build_args={build_args!r},
    hdl_toplevel={top!r},
    build_dir={build!r},
    timescale={timescale!r},
    waves={waves!r},
    always=True,
)

runner.test(
    hdl_toplevel={top!r},
    test_module={modules!r},
    test_dir={testdir!r},
    build_dir={build!r},
    results_xml={results!r},
    test_args={test_args!r},
    plusargs={plusargs!r},
    testcase={testcase!r},
    waves={waves!r},
)
'''


# ---------------------------------------------------------------------------
# flow lint
# ---------------------------------------------------------------------------

def lint(module_name: str | None = None, fix_top: bool = True) -> int:
    _, module = workspace.resolve(module_name)
    cfg = module.cfg["lint"]

    if cfg["tool"] != "verilator":
        raise Abort(
            f"linting with '{cfg['tool']}' is not wired up yet",
            hint="Currently supported: verilator",
        )

    binary = tools.require("verilator")
    sources = module.sources("design")
    if sources.is_empty():
        raise Abort(
            f"{module.name}: {module.cfg['sources']['design']} lists no source files",
            hint=f"Add a module with `flow add rtl <name> {module.name}`.",
        )

    argv = [binary, "--lint-only", "-Wall"]
    if not cfg["fatal"]:
        argv.append("-Wno-fatal")
    if fix_top and module.top_design:
        argv += ["--top-module", module.top_design]
    for incdir in sources.incdirs:
        argv.append(f"+incdir+{incdir}")
    for name, value in sources.defines.items():
        argv.append(f"+define+{name}" + (f"={value}" if value else ""))
    argv += [str(a) for a in cfg["args"]]

    waivers = module.path(cfg["waivers"])
    if waivers.is_file():
        argv.append(str(waivers))

    argv += [str(src) for src in sources.sources]

    logdir = module.lintdir
    logdir.mkdir(parents=True, exist_ok=True)
    log = logdir / f"{module.name}.log"

    ui.step(f"Lint: {module.name}  ({len(sources.sources)} file(s))")
    code = tools.run(argv, cwd=module.root, log=log)

    if code == 0:
        ui.ok(f"clean  ->  {log.relative_to(module.root)}")
    else:
        ui.fail(f"lint failed (exit {code})  ->  {log.relative_to(module.root)}")
    return code


# ---------------------------------------------------------------------------
# flow sim
# ---------------------------------------------------------------------------

def _timescale(value: str | None) -> tuple[str, str] | None:
    if not value:
        return None
    unit, _, precision = str(value).partition("/")
    return (unit.strip(), (precision or unit).strip())


def _framework(name: str | None) -> str:
    """Normalises the framework name from project.yaml or the command line."""
    which = str(name or "cocotb").lower()
    if which in ("systemverilog", "native"):
        which = "sv"
    if which not in FRAMEWORKS:
        raise Abort(
            f"test framework '{name}' is not wired up",
            hint=f"Currently supported: {', '.join(FRAMEWORKS)}",
        )
    return which


def _summarize_cocotb(results: Path) -> int:
    """Reads cocotb's JUnit XML and reports the outcome."""
    if not results.is_file():
        ui.warn("no results.xml -- outcome unknown")
        return 1

    tree = ET.parse(results)
    cases = list(tree.iter("testcase"))
    failed = [c for c in cases if c.find("failure") is not None or c.find("error") is not None]
    skipped = [c for c in cases if c.find("skipped") is not None]

    ui.hrule()
    for case in cases:
        name = case.get("name", "?")
        if case in failed:
            ui.fail(name)
        elif case in skipped:
            ui.warn(f"{name} (skipped)")
        else:
            ui.ok(name)

    total = len(cases)
    if failed:
        ui.fail(f"{len(failed)} of {total} test(s) failed")
        return 1
    ui.ok(f"{total} test(s) passed")
    return 0


def _summarize_sv(log: Path, code: int) -> int:
    """Reads the run log of a SystemVerilog testbench and reports the outcome."""
    text = log.read_text(encoding="utf-8", errors="replace") if log.is_file() else ""
    problems = [
        line.strip()
        for line in text.splitlines()
        if any(marker in line for marker in FAIL_MARKERS)
    ]

    ui.hrule()
    for line in problems[:5]:
        ui.fail(line)
    if len(problems) > 5:
        ui.note(f"... and {len(problems) - 5} more line(s), see {log.name}")

    if code != 0 or problems:
        ui.fail(f"simulation failed (exit {code})  ->  {log.name}")
        return code or 1
    if PASS_MARKER in text:
        ui.ok(PASS_MARKER)
        return 0

    ui.warn(f"no '{PASS_MARKER}' in the output -- outcome unclear")
    ui.note("A testbench should print TEST PASSED, or fail via $fatal.")
    return 0


def _collect_waves(testdir: Path, rundir: Path) -> None:
    """Moves dump.* out of the test directory into the run directory."""
    for path in testdir.glob("dump.*"):
        if path.suffix in WAVE_SUFFIXES:
            target = rundir / path.name
            target.unlink(missing_ok=True)
            path.rename(target)
            ui.note(f"moved {path.name} to {rundir.name}/")


def _run_cocotb(module, cfg, top: str, sources, defines: dict, build_args: list[str],
                wave_file: Path | None, waves_on: bool, testcase: str | None,
                dry_run: bool) -> int:
    modules = list(cfg["modules"])
    if not modules:
        raise Abort(
            f"{module.name}: sim.modules is empty",
            hint=f"Add a test with `flow add tb <name> {module.name}`.",
        )

    simulator = cfg["simulator"]
    rundir = module.rundir
    build = rundir / "build"
    results = rundir / "results.xml"
    results.unlink(missing_ok=True)

    # cocotb starts the simulator with cwd=test_dir; without an explicit path
    # the waveform would end up in the middle of the source tree.
    test_args: list[str] = []
    if waves_on and simulator == "verilator" and wave_file is not None:
        if wave_file.suffix == ".fst":
            build_args = [*build_args, "--trace-fst"]
        test_args += ["--trace-file", str(wave_file)]

    stamp = meta.fields()
    script = RUNNER.format(
        stamp=f"{stamp['date']} {stamp['time']}",
        simulator=simulator,
        sources=[str(s) for s in sources.sources],
        includes=[str(i) for i in sources.incdirs],
        defines=defines,
        build_args=build_args,
        top=top,
        modules=modules,
        testdir=str(module.path(cfg["testdir"])),
        build=str(build),
        results=str(results),
        plusargs=[str(p) for p in cfg["plusargs"]],
        testcase=testcase,
        test_args=test_args,
        waves=waves_on,
        timescale=_timescale(cfg["timescale"]),
    )

    runner_path = rundir / "run_sim.py"
    runner_path.write_text(script, encoding="utf-8")

    if dry_run:
        ui.step(f"Simulation: {module.name}  (dry run, nothing is executed)")
        ui.note(f"script: {runner_path}")
        ui.hrule()
        print(script)
        return 0

    tools.require({"icarus": "iverilog"}.get(simulator, simulator))

    ui.step(f"Simulation: {module.name}  (top={top}, {simulator}, cocotb, "
            f"{len(modules)} test module(s))")
    interpreter = tools.python(module.root)
    code = tools.run([interpreter, str(runner_path)], cwd=rundir)

    if waves_on:
        _collect_waves(module.path(cfg["testdir"]), rundir)

    return _summarize_cocotb(results) or code


def _sv_commands(module, cfg, top: str, sources, defines: dict, build_args: list[str],
                 plusargs: list[str], build: Path) -> tuple[list[str], list[str]]:
    """Builds the compile and run command for a plain SystemVerilog testbench."""
    simulator = cfg["simulator"]

    if simulator == "verilator":
        binary = tools.require("verilator")
        # -Wno-fatal: warnings belong to `flow lint`, they must not kill a run.
        compile_argv = [binary, "--binary", "-j", "0", "-Wno-fatal",
                        "--top-module", top, "--Mdir", str(build), "-o", "sim"]
        if cfg["timescale"]:
            compile_argv += ["--timescale", str(cfg["timescale"])]
        compile_argv += [f"+incdir+{inc}" for inc in sources.incdirs]
        compile_argv += [
            f"+define+{name}" + (f"={value}" if value else "")
            for name, value in defines.items()
        ]
        compile_argv += build_args + [str(src) for src in sources.sources]
        return compile_argv, [str(build / "sim"), *plusargs]

    if simulator == "icarus":
        binary = tools.require("iverilog")
        output = build / f"{top}.vvp"
        compile_argv = [binary, "-g2012", "-o", str(output), "-s", top]
        for inc in sources.incdirs:
            compile_argv += ["-I", str(inc)]
        compile_argv += [
            f"-D{name}" + (f"={value}" if value else "")
            for name, value in defines.items()
        ]
        compile_argv += build_args + [str(src) for src in sources.sources]
        return compile_argv, [tools.require("vvp"), str(output), *plusargs]

    raise Abort(
        f"simulator '{simulator}' is not wired up for framework 'sv'",
        hint="Currently supported: verilator, icarus",
    )


def _run_sv(module, cfg, top: str, sources, defines: dict, build_args: list[str],
            wave_file: Path | None, testcase: str | None, dry_run: bool) -> int:
    rundir = module.rundir
    build = rundir / "build"
    build.mkdir(parents=True, exist_ok=True)

    plusargs = [str(p) for p in cfg["plusargs"]]
    if testcase:
        plusargs.append(f"+TESTCASE={testcase}")

    defines = dict(defines)
    if wave_file is not None:
        # The testbench dumps under `WAVE_FILE` when WAVES is defined; the run
        # happens with cwd=rundir, so the relative name lands next to the log.
        defines["WAVES"] = None
        defines["WAVE_FILE"] = f'"{wave_file.name}"'

    compile_argv, run_argv = _sv_commands(
        module, cfg, top, sources, defines, build_args, plusargs, build
    )

    if dry_run:
        ui.step(f"Simulation: {module.name}  (dry run, nothing is executed)")
        ui.shell(compile_argv)
        ui.shell(run_argv)
        return 0

    log = rundir / SIM_LOG
    log.unlink(missing_ok=True)

    ui.step(f"Simulation: {module.name}  (top={top}, {cfg['simulator']}, SystemVerilog)")
    code = tools.run(compile_argv, cwd=module.root, log=build / BUILD_LOG)
    if code != 0:
        ui.fail(f"compile failed (exit {code})  ->  build/{BUILD_LOG}")
        return code

    if testcase:
        ui.note(f"+TESTCASE={testcase} -- the testbench decides what that means")

    code = tools.run(run_argv, cwd=rundir, log=log)
    return _summarize_sv(log, code)


def sim(module_name: str | None = None, testcase: str | None = None,
        open_waves: bool = False, dry_run: bool = False,
        framework: str | None = None) -> int:
    _, module = workspace.resolve(module_name)
    cfg = module.cfg["sim"]
    which = _framework(framework or cfg["framework"])

    top = module.sim_top(which)
    if not top:
        raise Abort(
            f"{module.name}: no top module for framework '{which}'",
            hint=(
                "Set top.tb in project.yaml, or create one with `flow add tb --sv <name>`."
                if which == "sv"
                else "Set top.design in project.yaml."
            ),
        )

    sources = module.sources("filelist")
    if sources.is_empty():
        raise Abort(f"{module.name}: {module.cfg['sources']['filelist']} lists no source files")

    rundir = module.rundir
    rundir.mkdir(parents=True, exist_ok=True)

    defines = dict(sources.defines)
    for entry in cfg["defines"]:
        name, _, value = str(entry).partition("=")
        defines[name] = value or "1"

    waves_mode = str(cfg["waves"]).lower() if cfg["waves"] else "none"
    waves_on = waves_mode not in ("none", "false", "0")
    build_args = [str(a) for a in cfg["build_args"]]
    wave_file: Path | None = None

    if waves_on:
        suffix = "fst" if waves_mode == "fst" else "vcd"
        if which == "sv" and cfg["simulator"] == "icarus" and suffix == "fst":
            ui.warn("icarus writes VCD here -- falling back to sim.waves = vcd")
            suffix = "vcd"
        wave_file = rundir / f"{top}.{suffix}"
        wave_file.unlink(missing_ok=True)
        if which == "sv" and cfg["simulator"] == "verilator":
            build_args.append("--trace-fst" if suffix == "fst" else "--trace")

    if which == "cocotb":
        code = _run_cocotb(module, cfg, top, sources, defines, build_args,
                           wave_file, waves_on, testcase, dry_run)
    else:
        code = _run_sv(module, cfg, top, sources, defines, build_args,
                       wave_file, testcase, dry_run)

    if dry_run:
        return code

    if wave_file is not None and wave_file.is_file():
        ui.note(f"waveform: {wave_file.relative_to(module.root)}")

    if open_waves:
        try:
            wave(module_name)
        except Abort as exc:
            ui.warn(str(exc))

    return code


# ---------------------------------------------------------------------------
# flow wave
# ---------------------------------------------------------------------------

def _newest_wave(rundir: Path) -> Path | None:
    candidates = [
        path
        for path in rundir.rglob("*")
        if path.is_file() and path.suffix in WAVE_SUFFIXES
    ]
    return max(candidates, key=lambda p: p.stat().st_mtime, default=None)


def wave(module_name: str | None = None, viewer: str | None = None) -> int:
    _, module = workspace.resolve(module_name)
    target = _newest_wave(module.rundir)

    if target is None:
        raise Abort(
            f"{module.name}: no waveform in {module.cfg['sim']['rundir']}",
            hint="Simulate first: `flow sim`",
        )

    chosen = viewer or next((v for v in VIEWERS if tools.find(v)), None)
    if chosen is None:
        raise Abort(
            "No waveform viewer found",
            hint="Install one with: pacman -S gtkwave  (or: paru -S surfer-bin)",
        )
    tools.require(chosen)

    ui.step(f"Waveform: {target.relative_to(module.root)}")
    tools.spawn([chosen, str(target)])
    return 0


# ---------------------------------------------------------------------------
# flow clean
# ---------------------------------------------------------------------------

def clean(module_name: str | None = None, all_modules: bool = False) -> int:
    if all_modules:
        ws = workspace.require_workspace()
        targets = ws.modules()
    else:
        _, module = workspace.resolve(module_name)
        targets = [module]

    for module in targets:
        removed = []
        for path in (module.rundir, module.lintdir):
            if not path.is_dir():
                continue
            for entry in path.iterdir():
                if entry.name in (".gitkeep", "waivers.vlt"):
                    continue
                if entry.is_dir():
                    shutil.rmtree(entry)
                else:
                    entry.unlink()
                removed.append(entry.name)
        ui.step(f"Cleaned: {module.name}")
        ui.note(f"removed {len(removed)} entry/entries" if removed else "was already clean")
    return 0
